#!/usr/bin/env sh

# global settings
yabai -m config external_bar                  all:30:0
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xddd5c4a1
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --remove space_created_sketchybar 2>/dev/null
yabai -m signal --remove space_destroyed_sketchybar 2>/dev/null
yabai -m signal --add label=space_created_sketchybar event=space_created action="sketchybar --trigger space_list_change"
yabai -m signal --add label=space_destroyed_sketchybar event=space_destroyed action="sketchybar --trigger space_list_change"

echo "yabai configuration loaded.."
