tap "aws/tap"
tap "golangci/tap"

# Core shell & terminal
brew "zsh"
brew "zsh-syntax-highlighting"
brew "tmux"
brew "reattach-to-user-namespace"
brew "pure"
brew "git"
brew "curl"
brew "wget"
brew "vim"
brew "neovim"

# System utilities
brew "ack"
brew "autossh"
brew "coreutils"
brew "dos2unix"
brew "findutils"
brew "gawk"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnupg"
brew "htop"
brew "httrack"
brew "ifstat"
brew "jq"
brew "mas"
brew "ncdu"
brew "neofetch"
brew "nmap"
brew "parallel"
brew "the_silver_searcher"
brew "tig"
brew "tre"
brew "tree"
brew "watch"
brew "wdiff"
brew "ranger"

# Developer tools
brew "autoconf"
brew "automake"
brew "binutils"
brew "gh"
brew "grip"
brew "krb5"

# Languages & version managers
brew "go"
brew "golangci/tap/golangci-lint"
brew "node-build"
brew "nodenv"
brew "newman"
brew "pyenv"
brew "rbenv"
brew "ruby-build"
brew "ruby"

# Media processing (CLI)
brew "ffmpeg"
brew "imagemagick"

# Cloud & infra
brew "awscli", link: false
brew "aws/tap/aws-sam-cli"

# Other
brew "haskell-stack"
